[package]
name = "lotsa_rust"
version = "0.1.0"
authors = ["David Simon <david.mike.simon@gmail.com>"]

[dependencies]
prost = "0.4.0"
prost-derive = "0.4.0"
bytes = "0.4.8"

[build-dependencies]
prost-build = "0.4.0"