version: "3.7"
services:
  dev:
    build: lotsa-game-template
    working_dir: /app
    volumes:
      - .:/app
      - cargo-common:/cargo-common
      - cargo-lotsa:/cargo-lotsa
    environment:
      - CARGO_HOME=/cargo-common
      - CARGO_TARGET_DIR=/cargo-lotsa
    ports:
      - "8000:8000"

volumes:
  cargo-common:
  cargo-lotsa:
