edition = "2018"
tab_spaces = 2

# unstable_features = true
#
# error_on_line_overflow = true
# error_on_unformatted = true
# fn_single_line = true
# format_strings = true
# match_block_trailing_comma = true
# merge_imports = true
# newline_style = "Unix"
# normalize_comments = true
# reorder_impl_items = true
# use_field_init_shorthand = true
# wrap_comments = true
