use actix::{Actor, StreamHandler};
use actix_web::{fs, server, ws, App, HttpRequest, HttpResponse};

struct LotsaWebsocketActor;

impl Actor for LotsaWebsocketActor {
  type Context = ws::WebsocketContext<Self>;
}

impl StreamHandler<ws::Message, ws::ProtocolError> for LotsaWebsocketActor {
  fn handle(&mut self, msg: ws::Message, ctx: &mut Self::Context) {
    match msg {
      ws::Message::Ping(msg) => ctx.pong(&msg),
      ws::Message::Text(_text) => ctx.text("Hello there"),
      _ => (),
    }
  }
}

fn webpack_dist() -> fs::StaticFiles<()> {
  fs::StaticFiles::new("www/dist")
    .expect("find www/dist directory generated by webpack") // TODO
    .index_file("index.html")
}

fn websocket_handler(req: &HttpRequest<()>) -> Result<HttpResponse, actix_web::error::Error> {
  ws::start(req, LotsaWebsocketActor)
}

pub fn main() {
  server::new(|| {
    App::new()
      .resource("/ws/", |r| r.f(|req| websocket_handler(req)))
      .handler("/", webpack_dist())
  })
  .bind("127.0.0.1:8088")
  .expect("bind to open port") // TODO
  .run()
}
