use actix_web::{fs, server, App};

pub fn main() {
  server::new(|| {
    let root = fs::StaticFiles::new("www/dist")
      .expect("find www/dist directory generated by webpack") // TODO
      .index_file("index.html");
    App::new().handler("/", root)
  })
  .bind("127.0.0.1:8088")
  .expect("bind to open port") // TODO
  .run()
}
